# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version={{ minecraft_version }}
loader_version={{ fabric_loader_version }}
loom_version={{ loom_version }}

# Mod Properties
mod_version={{ mod_version }}
maven_group={{ package_name }}
archives_base_name={{ mod_id }}

# Dependencies
fabric_version={{ fabric_api_version }}