"""Package project output: generate zip, copy jar, save blueprint."""

import json
import shutil
import zipfile
from pathlib import Path


def _write_readme(output_dir: Path, blueprint: dict) -> None:
    """Generate README.md explaining how to install and use the generated mod."""
    mod_id = blueprint["mod_id"]
    mod_name = blueprint.get("mod_name", mod_id)
    content = f"""# {mod_name}

A Fabric mod automatically generated by ModSmith.

## Installation

1. Install Fabric Loader for the corresponding Minecraft version.
2. Download [Fabric API](https://modrinth.com/mod/fabric-api) and place it in the `mods/` folder.
3. Place `{mod_id}-*.jar` into the `mods/` folder.
4. Launch Minecraft (Fabric profile).

## Development

If you want to continue development, unzip `{mod_id}-src.zip`, open it with IntelliJ IDEA, and run `./gradlew build`.

## Blueprint

This mod was generated from the following blueprint:

```json
{json.dumps(blueprint, indent=2, ensure_ascii=False)}
"""
    (output_dir / "README.md").write_text(content, encoding="utf-8")

def _zip_project(project_dir: Path, zip_path: Path) -> None:
    """Package the project directory into a zip file (excluding build directory and .gradle cache)."""
    EXCLUDE_DIRS = {"build", ".gradle", ".idea", "run"}
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in project_dir.rglob("*"):
            if path.is_dir():
                continue

            # Skip contents in excluded directories

            rel_parts = path.relative_to(project_dir).parts
            if any(part in EXCLUDE_DIRS for part in rel_parts):
                continue
            zf.write(path, path.relative_to(project_dir))


def _find_jar(project_dir: Path) -> Path | None:
    """Find the compiled jar under build/libs/ (excluding sources jar)."""
    libs_dir = project_dir / "build" / "libs"
    if not libs_dir.exists():
        return None
    jars = [
        p for p in libs_dir.glob("*.jar")
        if not p.name.endswith("-sources.jar") and not p.name.endswith("-dev.jar")
    ]
    if not jars:
        return None
    # Return the most recent one
    return max(jars, key=lambda p: p.stat().st_mtime)


def package_output(
    blueprint: dict,
    project_dir: Path,
    output_dir: Path,
) -> dict:
    """Package project output: zip, jar, blueprint, README.
    Args:
        blueprint: Blueprint dictionary.
        project_dir: Generated project directory.
        output_dir: Packaging output directory.

    Returns:
        A dictionary containing the paths of packaging results.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    mod_id = blueprint["mod_id"]
    results = {}

    # 1. Package source zip
    src_zip = output_dir / f"{mod_id}-src.zip"
    _zip_project(project_dir, src_zip)
    results["source_zip"] = src_zip
    print(f"📦 Source zip generated: {src_zip}")

    # 2. Copy compilation artifact jar
    jar = _find_jar(project_dir)
    if jar:
        dest_jar = output_dir / jar.name
        shutil.copy2(jar, dest_jar)
        results["jar"] = dest_jar
        print(f"📦 Compilation artifact copied: {dest_jar}")
    else:
        print("⚠️ Compiled jar not found. Please confirm compilation succeeded.")

    # 3. Save blueprint JSON
    blueprint_path = output_dir / f"{mod_id}-blueprint.json"
    blueprint_path.write_text(
        json.dumps(blueprint, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    results["blueprint"] = blueprint_path
    print(f"📦 Blueprint saved: {blueprint_path}")

    # 4. Generate README
    _write_readme(output_dir, blueprint)
    results["readme"] = output_dir / "README.md"
    print(f"📦 README generated: {results['readme']}")

    return results    